### ISSUE TITLE
Associate issues with proper release milestone

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#519]
Per @lfunkhouser we are not to list individual issues that were closed or fixed under the Resources/Known Issues page our our Solutions site.  The direction we'd like to move towards is providing our users the ability to click on a link and get a filtered list of all issues addressed for a particular release. An example on how this should function can be found [here.](http://solutions.arcgis.com/defense/help/distance-direction/arcmap/known-issues-for-distance-and-direction-in-arcmap.htm)

The only exception to listing individual issues would be for issues that specifically address items previously listed under the "Known Issues" section or issues that originate from tech support.  At this point the issue would be listed separately under its associated release.  See example [here.](http://solutions.arcgis.com/defense/help/coordinate-conversion/resources/release-notes.htm) 

The section is:

All GitHub Issues closed or fixed for this release (includes ArcGIS Pro as well as ArcMap): [Link to Filtered list](https://github.com/Esri/distance-direction-addin-dotnet/milestone/1?closed=1)

In order to mimic this behavior across our issues we will need to make sure each issue is tagged with the appropriate Milestone.  The following will need to be performed:

- [ ] Create new release milestone.
- [ ] Associate issues with this new milestone.
- [ ] Create a new release (This is something that is not necessary for the sort to work, however, might be a good idea for issue management.)

FYI @dfoll @topowright

**Comment by lfunkhouser** [comment]
The direction from planning was that @dfoll was to work this out as the team's doc lead and present the best way forward for the structure of the Issues addressed in the Release Notes.

**Comment by lfunkhouser** [comment]
Closing. Way forward is to list them out. Since moving to Sprints/Iteration Milestones, there is no easy way to link to the issues addressed. GitHub labels cannot be used. If the label is deleted, the link would be broken. Example of way forward is in http://solutions.arcgis.com/defense/help/gridded-reference-graphic/resources/release-notes.htm.
