### ISSUE TITLE
Label DD Ellipses in Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#543]
### Background
Users need to have labels on features created by Distance and Direction. Creating this layer package will enable us to advance development on creating labels in ArcGIS Pro.

### Current State
We are unable to create labels for any features being created for Distance and Direction in ArcGIS Pro.

### Expected Result

Functionality is implemented
Tests written
Tested on Pro 2.1, 2.2
Tested in Distance and Direction 2.1 and 2.2
Tested in Military Tools 2.1 and 2.2
Documented in Distance and Direction and Military Tools

### Tasks to be done - Last update ~~23 May 2018~~ 30 May 2018
- [x] Design how the user would expect labels to happen
- [x] Verify that layer package matches other tabs (circles is the first tab that was worked on) 
- [x] Review the manual checklist test
- [x] Reveiw the workflow
- [x] Update / review the CMS resources notes
- [x] Review the homepage for Military Tools and Distance and Direction 
- [X] Hook up delete all
- [x] Switch from drawing graphics to drawing features
- [x] Add all feature class types for DD to ToC
- [x] Featureclasses should be inside a featuredataset
- [x] enable labels
- [x] Writing the arcade scripts for label expressions
- [x] (ADDED) Final global check of the feature class code implementation to add better failure checking and reporting (Chris)
 
### Verify
- [x] Features are created in default database
- [x] Feature are deleted from default database 
- [x] Labels are using the correct style
- [x] Verify Update documentation

### Background information
- [ ]location of the layer package
https://github.com/Esri/distance-direction-addin-dotnet/compare/csm/%23541-pro-features

**Comment by BobBooth** [comment]
While working on Pro label expression for ellipse features with @topowright  and @ACueva, identified that the labels for ellipses in ArcMap were cluttered/verbose. Chose to simplify the expression in Pro.  Submitted this issue to fix the labels to match in ArcMap:
https://github.com/Esri/distance-direction-addin-dotnet/issues/573

**Comment by csmoore** [comment]
Looks like the Layer Package / Feature Class is complete for Ellipse Layer unless there are additional enhancements

![image](https://user-images.githubusercontent.com/3090809/40685131-66ad6492-6361-11e8-9037-983cdd785430.png)

**Comment by csmoore** [comment]
Began work in branch https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23543-ellipse-labels-pro 

I did see the issue/bug noted in #572 with the Ellipse attributes - angle was incorrect (using radians) - that was showing up in the exports (now in the feature layer) :  

![image](https://user-images.githubusercontent.com/3090809/40732141-a89c1a98-6400-11e8-91ce-7ad71b2a69ba.png)

So that should be fixed with this issue/branch : 

![image](https://user-images.githubusercontent.com/3090809/40733331-52e6080e-6403-11e8-92cc-06c414f0ead2.png)

**Comment by csmoore** [comment]
The work for ellipses is completed in PR #583 

Adding an additional dev task to this issue to do a final global check of the feature class implementation, for instance to add better failure checking and reporting since we have noticed during the testing to date that when features fail to add/draw that there is no information reported to the user (though there should have been)

**Comment by csmoore** [comment]
Added error checks in PR #584 ( note this PR depends on PR #583 which is still pending review )
