### ISSUE TITLE
Label DD Rings in Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#544]
### Background
Users need to have labels on features created by Distance and Direction. Creating this layer package will enable us to advance development on creating labels in ArcGIS Pro.

### Current State
We are unable to create labels for any features being created for Distance and Direction in ArcGIS Pro.

### Expected Result

Functionality is implemented
Tests written
Tested on Pro 2.1, 2.2
Tested in Distance and Direction 2.1 and 2.2
Tested in Military Tools 2.1 and 2.2
Documented in Distance and Direction and Military Tools

### Tasks to be done - Last update 23 May 2018
- [x] Updated MT and DD builds with one pdf and added release notes
- [x] Design how the user would expect labels to happen - BB/AC
- [x] Verify that layer package matches other tabs (circles is the first tab that was worked on) 
- [x] Review the manual checklist test - Avi
- [x] Reveiw the workflow - Lyle
- [x] Update CMS resources tab for DD
   - [x] Update June 2018 Release - Derek
   - [x] Update Contents  - Derek
- [x] Review CMS resources notes for DD - Avi
- [x] Update CMS resources for MT
   - [x] Update June 2018 Release - Derek
    - [x] Update Contents  - Derek
- [x] Review CMS resources for MT
- [x] Update DD homepage - Lyle
- [x] Review DD homepage
- [x] Update MT homepage - Derek
- [x] Review the homepage for Military Tools
- [x] Update Defense What's New page   -Derek
- [x] Review Defense What's New page - Derek
- [x] Review homepage for DD
- [x] Hook up delete all
- [x] Share a list of questions with the team - Chris

- [x] Switch from drawing graphics to drawing features
- [x] Verify drawing/labeling portion of checklist test for range rings - Derek
- [x] Add all feature class types for DD to ToC
- [x] Featureclasses should be inside a featuredataset
- [x] enable labels
- [x] Writing the arcade scripts for label experssions  - BB/AC 
- [x] Create 2 layer packages with sample features (schema only and one with data)  - BB/AC PR is here: https://github.com/Esri/distance-direction-addin-dotnet/pull/566
- [x] update the label color and style
- [x] update the label for unit of measure

### Verify
- [x] Features are created in default database
- [x] Feature are deleted from default database 
- [x] Labels are using the correct style
- [x] Verify Update documentation

### Background information
location of the layer package
https://github.com/Esri/distance-direction-addin-dotnet/compare/csm/%23541-pro-features

**Comment by ACueva** [comment]
Checklist was updated in this PR: https://github.com/ArcGIS/solutions-defense-test-catalog/pull/144

**Comment by ACueva** [comment]
LPK schema contains a column called "RR_Type", this is to be used to differentiate the type of feature being drawn by the Range Rings, either a ring, or a radial.
We will use an Arcade expression to differentiate between these two types and only label rings.

**Comment by csmoore** [comment]
@ACueva - good catch - I can repro this error and do see what is going on here: a separate thread queues up these lpkx-exists checks + add requests before the main thread finally adds the lpkx to the map. Just need to move the initial check for this to the main thread.

**Comment by csmoore** [comment]
Added fix to existing open PR #583: https://github.com/Esri/distance-direction-addin-dotnet/pull/583/commits/b61e79c125102c7eed5eac850009c58c9252067f to address [issue noted above with adding lpkx multiple times](https://github.com/Esri/distance-direction-addin-dotnet/issues/544#issuecomment-393351045)

**Comment by ACueva** [comment]
Removing Development label as @csmoore has addressed the multiple lpk issue in PR #583

**Comment by ACueva** [comment]
@dfoll and I have worked on the remaining doc related updates.  Additional work is still necessary pertaining to the folder structure.  This includes updates to our Jenkins build.

**Comment by dfoll** [comment]
G-Dev Jenkins label is on because (as of 1June) both DD and MT are not building the final folder structure and pulling the pdfs that we want

**Comment by dfoll** [comment]
Ran through the creating/labeling portion of the checklist test for range rings. Did not switch over to cucumber format, as there were no changes needed

**Comment by topowright** [comment]
I have updated the build for jenkins and submitted a PR that I have added @ACueva to review

**Comment by ACueva** [comment]
Verified doc both on solutions site and PDF site.
Only question is pertaining the PDF in the Released Notes:
The solutions site shows known issues like this:
![2018-06-04_13-52-56](https://user-images.githubusercontent.com/3093940/40941099-b2d66ca0-67fe-11e8-9a33-f1b70f1e83e6.jpg)

The Release Notes pdf shows it like this:
![snag_1edf31d5](https://user-images.githubusercontent.com/3093940/40941117-be96209e-67fe-11e8-9312-cf2d5fe0d4cd.png)

It's fairly minor, any ideas why "No known issues" isn't being displayed in the PDF? @dfoll @topowright

**Comment by ACueva** [comment]
Updated MT June 2018 CMS content to reflect "No Known Issues" under Issues addressed.

Changed DD June 2018 CMS. Removed "Attribute table for rings is not being populated." for known issue in ArcMap.  This has been addressed in: https://github.com/Esri/distance-direction-addin-dotnet/issues/371

![2018-06-04_14-28-43](https://user-images.githubusercontent.com/3093940/40942675-d21d2d60-6803-11e8-8be3-ad36a629b5bc.jpg)
![2018-06-04_14-29-03](https://user-images.githubusercontent.com/3093940/40942678-d3bc0326-6803-11e8-8e30-b58c87bbb4bd.jpg)

**Comment by ACueva** [comment]
Remaining task, verify Doc changes in Military Tools & DD - Known Issues section
