### ISSUE TITLE
Export Circles in ArcGIS Pro

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#559]
#### Tasks to be done

- [x] The doc needs to explain in a concise way what is happening in ArcGIS Pro and ArcMap (BB- done)
- [x] Review the doc changes
- [x] Wire up save as functionality for feature class
- [x] Wire up save as functionality for shapefile
- [x] Wire up save as functionality for KMZ
- [x] Remove Previous Graphics List / Feature Class Implementation in source code once the new export is fully implemented / working (dev)

#### Verify
- [x] Save as feature class works - Avi
- [x] Save as shapefile works - Avi
- [x] Save as KMZ works (Portal and ArcGIS Earth) - Avi

**Comment by csmoore** [comment]
Beginning this dev work - now that everything is already using features I think this should be straight-forward - mainly removing code that no longer applies - but I do think only one of the export issues ( #558 , #559, #560, #561 ) can be worked on at a time since they all use the same export method.

**Comment by csmoore** [comment]
Work started in branch: https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23559-export-circles - this seems to mainly involve just changing the previous export code to a simple GP Copy Features.

**Comment by csmoore** [comment]
Export / SaveAs should now be wired up in PR #588 

A task was added above to "Remove Previous Graphics List / Feature Class Implementation" once the new export is fully implemented / working

The exported / copied layers pick up the symbology of the source layer, but oddly not the label properties - so not sure what the expected behavior of the export layers should be (I actually wasn't even expecting the symbology)

![image](https://user-images.githubusercontent.com/3090809/40847031-34423fbc-6589-11e8-8b9b-ff8c87e8ca65.png)

**Comment by ACueva** [comment]
Verified Shape File, Feature Class work:
![2018-06-01_12-40-11](https://user-images.githubusercontent.com/3093940/40860124-17970d56-6599-11e8-8505-8c66fe8a45c5.jpg)
Verified KMZ works:
![2018-06-01_12-39-59](https://user-images.githubusercontent.com/3093940/40860140-25a3ddd4-6599-11e8-94cd-3eabd688bb99.jpg)

**Comment by BobBooth** [comment]
@ACueva & @kgonzago  - it looks like the exported feature class and shapefile do not retain the symbology, but the comment by @csmoore  from 5 hours ago it was retaining the symbology.  ?? Seems like that would be a desirable thing.

**Comment by kgonzago** [comment]
@BobBooth Can you add a new issue about that? Symbology and labels should be come over in the export process.

**Comment by ACueva** [comment]
@csmoore, @kgonzago, how much effort would it be to have the arcade expression be exported with all 3 of our possible outputs?
Also, label style is also not being exported, is this possible?

**Comment by kgonzago** [comment]
@ACueva I'll look into arcade expressions and label styles issues.

**Comment by csmoore** [comment]
I am baffled why the symbology is being applied on my Pro (2.1) export layers but not others, but probably to get the layers symbology and labels working consistently everywhere we will have to:

1. Create individual layer files (lyrx) for lines, circles, ellipses, and rings
2. Call GP tool ApplySymbologyFromLayer_management on the new/export layer

My only concern is the timeline since there is a delay and thread interactions between when a layer is requested to be added (in this case by the CopyFeatures GP tool) and it actually gets added to the map.

**Comment by ACueva** [comment]
@csmoore @kgonzago, Speaking with @lfunkhouser on Friday, if this isn't something that can be tackled fairly easily (under 4 hours), we are to address this in a future release.  I'll log an issue for this enhancement.

**Comment by csmoore** [comment]
I can  do a quick test with circles layer ( < 1.5 hours) and if there are any issues I can abandon the ApplySymbologyFromLayer approach

**Comment by csmoore** [comment]
I was not able to get applying the layer symbology to work from the Addin (Pro SDK) or from python: 
```
arcpy.management.ApplySymbologyFromLayer("SampleExport", r"Distance And Direction\Circles", None, "DEFAULT")
```

This seems like a bug in these environments since I can get this GP tool to run successfully is when it was run from the Pro Geoprocessing Frame/UI - so we may have to doc this step/workaround if the user wants apply the same symbology/labeling to the export layer ( @ACueva @topowright @dfoll ) : 

![image](https://user-images.githubusercontent.com/3090809/40934034-76eefa9c-6801-11e8-87ec-0a22c122838e.png)

The testing/work was done in this branch: https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23559-apply-lyrx-to-export

**Comment by dfoll** [comment]
I agree with @topowright that this issue is verified and working. I believe there should be a github issue created with the enhancement of the exported feature class having the same labels and symbology before this issue is closed and taken off our radar
