### ISSUE TITLE
Export Rings in ArcGIS Pro

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#560]
#### Tasks to be done

- [x] The doc needs to explain in a concise way what is happening in ArcGIS Pro and ArcMap
- [x] Review the doc changes
- [x] Wire up save as functionality for feature class
- [x] Wire up save as functionality for shapefile
- [x] Wire up save as functionality for KMZ

#### Verify
- [x] Save as feature class works
- [x] Save as shapefile works
- [x] Save as KMZ works (Portal and ArcGIS Earth)

**Comment by kgonzago** [comment]
Taking on the task of verifying from our latest build.

**Comment by csmoore** [comment]
An action item from today's sprint review to complete #544 + #560 was to remove the "Radials" column. This was partially done in PR #602. 

IMPORTANT: this attribute will also need to be removed from the layer package (lpkx) to be fully completed - this is why this column still appears in Pro (with Nulls below)

@topowright @lfunkhouser @dfoll @ACueva @kgonzago @BobBooth 

![image](https://user-images.githubusercontent.com/3090809/41005520-d5fd09d0-68eb-11e8-8bc1-bcc4b45096d5.png)
