### ISSUE TITLE
Export Ellipse in ArcGIS Pro

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#561]
#### Tasks to be done

- [x] The doc needs to explain in a concise way what is happening in ArcGIS Pro and ArcMap
- [x] Review the doc changes
- [x] Wire up save as functionality for feature class
- [x] Wire up save as functionality for shapefile
- [x] Wire up save as functionality for KMZ

#### Verify
- [x] Save as feature class works
- [x] Save as shapefile works
- [x] Save as KMZ works (Portal and ArcGIS Earth)
