### ISSUE TITLE
Update ArcMap addin to use new labeling styles

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#573]
### Tasks to be done 25 May 2018
- [x] Update label for Lines
- [x] Update label for Circles 
- [x] Update label for Ellipses
- [x] Update label for Rings

### Background: 
Now that we have labels in ArcGIS Pro ArcMap needs to follow the same patteren

### Expected results: 
In ArcGIS Pro we use arcade scripts to drive the labels, which is not able to be done in ArcMap, but the same labels should be present in ArcMap
![image](https://user-images.githubusercontent.com/5488313/40563971-b86ba594-601b-11e8-93f8-a3f0655b6dc5.png)

### Original Issue
In the course of working on the Pro feature labels for Ellipse features, @topowright identified that the current ArcMap ellipse labels are verbose, cluttering the display. 
The new label expression for Pro will drop the words "Axis" and "Orientation" from the labels, in favor of simply
Major:  [number] [units]
Minor: [number] [units]
Angle:  [number] [units]

Old labels in ArcMap:
![image](https://user-images.githubusercontent.com/3801392/40559687-9daf76e0-6025-11e8-9fdc-9247b51c0d55.png)

**Comment by dfoll** [comment]
@topowright @kgonzago @lfunkhouser build 12  in ....\Commercial\Solutions\DefenseSolutions\DistanceAndDirection\Testing can be used to test this functionality
